package pl.pjay.enguage;

public class PhrasalsBase {
    String meanings[] = {"mieć zamiar coś zrobić",
            "ścigać",
            "zgadzać się",
            "być nieobecnym",
            "lecieć w telewizji",
            "być poza domem",
            "zajmować się czymś",
            "napotkać, natknąć się",
            "zdarzyć się",
            "obniżać się",
            "odziedziczyć",
            "powieść się",
            "wyjść na jaw",
            "dojść do siebie",
            "dojść do siebie",
            "pojawić się (temat w dyskusji)",
            "równać się",
            "rozlecieć się",
            "zawrócić",
            "uciec się do",
            "odstawać",
            "spaść",
            "zakochać się",
            "odpaść",
            "kłócić się z",
            "nie udać się",
            "zdradzić kogoś",
            "oddać",
            "poddać się",
            "wydzielać coś",
            "prowadzić do",
            "wydawać",
            "współpracować",
            "unikać",
            "sugerować",
            "gnębić kogoś",
            "zabrać się do",
            "robić progres",
            "dojść do siebie",
            "unikać",
            "przetrwać",
            "okrążyć",
            "wrócić",
            "zostać zrozumianym",
            "wziąć udział",
            "badać",
            "wybuchnąć",
            "kontynuować",
            "sprawdzić",
            "podjąć trud",
            "wzrastać",
            "patrzeć z pogardą na",
            "szukać",
            "odwiedzić",
            "analizować",
            "rozważać",
            "oglądać",
            "przejrzeć",
            "sprawdzić (w książce) ",
            "odwiedzić kogoś",
            "podziwiać",
            "udać się w kierunku",
            "sądzić o czymś",
            "uciec",
            "zdołać dostrzec",
            "zdecydować się",
            "wymyślić",
            "nadrobić",
            "wyprzedzić",
            "odsunąć od siebie",
            "oddalić się",
            "wycofać się",
            "zburzyć",
            "wspierać, kibicować",
            "zatrzymać się",
            "usunąć",
            "założyć ubranie",
            "zatrzymać się na poboczu",
            "odłożyć (pieniądze)",
            "odłożyć coś z powrotem",
            "odłożyć (pieniądze)",
            "tłumić",
            "wysunąć",
            "zainstalować",
            "przełożyć",
            "ubrać się",
            "ugasić ogień",
            "przenocować kogoś",
            "budować",
            "tolerować",
            "stać i nic nie robić",
            "nie brać udziału",
            "odsunąć się",
            "być gotowym",
            "ustępować",
            "oznaczać",
            "być w zastępstwie",
            "wyróżniać się",
            "przeciwstawiać się",
            "unikać",
            "zostać",
            "zostać w domu",
            "pozostać dłużej",
            "być poza domem",
            "zostać na noc",
            "nie kłaść się spać",
            "przypominać kogoś",
            "wycofać",
            "zapisać",
            "nabrać kogoś",
            "zdjąć ubranie",
            "zatrudniać",
            "przejąć kontrolę",
            "lubić",
            "rozpocząć naukę czegoś",
            "odmówić",
            "odmówić",
            "pójść spać",
            "atakować",
            "okazać się",
            "wywrócić do góry nogami",
            "zwiększyć, pojawić się",
            "przeciwdziałać",
            "pracować nad czymś długo",
            "wiedzieć jak uniknąć problemów",
            "zrzucać",
            "pracować nad czymś",
            "trenować",
            "denerwować"};

    String options[][] = {{"be about to", "come about"},
            {"fall off", "be after"},
            {"be for", "give on to"},
            {"go off", "be off"},
            {"be on", "stay on"},
            {"put out", "be out"},
            {"be up to", "come to"},
            {"fall apart", "come across"},
            {"come about", "get around"},
            {"get down to", "come down"},
            {"come into", "give out"},
            {"go in", "come off"},
            {"come out", "fall out with"},
            {"fall back", "come round"},
            {"come to", "look into"},
            {"turn out", "come up"},
            {"come up to", "stand by"},
            {"put out", "fall apart"},
            {"fall back", "stay out"},
            {"take down", "fall back on"},
            {"fall behind", "put forward"},
            {"stand back", "fall down"},
            {"fall for", "put somebody up"},
            {"pull for", "fall off"},
            {"fall out with", "make out"},
            {"get round", "fall through"},
            {"give somebody away", "come out"},
            {"put down", "give back"},
            {"give in", "stay up"},
            {"fall off", "give off"},
            {"give on to", "stand up to"},
            {"give in", "give out"},
            {"get along", "make for"},
            {"take off", "get around"},
            {"get at", "work on"},
            {"get along", "get somebody down"},
            {"get down to", "look through"},
            {"pull for", "get on"},
            {"get over", "pull apart"},
            {"be out", "get round"},
            {"get through", "come up to"},
            {"get around", "go around"},
            {"go back", "fall behind"},
            {"make of", "go down"},
            {"go in", "take to"},
            {"get down to", "go into"},
            {"go off", "pull over"},
            {"stand in", "go on"},
            {"go over", "make for"},
            {"put on", "go to"},
            {"go up", "make up"},
            {"fall down", "look down on"},
            {"look for", "come round"},
            {"put somebody up", "look in"},
            {"look into", "turn in"},
            {"work up", "look on"},
            {"look over", "look up"},
            {"get around", "look through"},
            {"look up", "come about"},
            {"be up to", "look somebody up"},
            {"look up to", "give in"},
            {"put forward", "make for"},
            {"make of", "take after"},
            {"turn down", "make off"},
            {"make out", "work around"},
            {"go into", "make up one's mind"},
            {"make up", "get over"},
            {"go up", "make up for"},
            {"pull ahead", "take on"},
            {"turn out", "pull apart"},
            {"pull away", "go over"},
            {"get round", "pull back"},
            {"pull down", "get down to"},
            {"fall out with", "pull for"},
            {"pull in", "get on"},
            {"fall off", "pull off"},
            {"pull on", "give on to"},
            {"stand out", "pull over"},
            {"put aside", "give back"},
            {"make off", "put away"},
            {"put by", "make out"},
            {"take down", "put down"},
            {"put forward", "pull away"},
            {"work up", "put in"},
            {"put off", "take over"},
            {"pull ahead", "put on"},
            {"put out", "get at"},
            {"look somebody up", "put somebody up"},
            {"put up", "look up"},
            {"work up", "put up with"},
            {"stand about", "stay on"},
            {"pull down", "stand aside"},
            {"stand back", "look down on"},
            {"get on", "stand by"},
            {"stand down", "fall for"},
            {"make up", "stand for"},
            {"stand in", "be on"},
            {"come up", "stand out"},
            {"stand up to", "stand down"},
            {"stand out", "stay away"},
            {"stay behind", "look in"},
            {"be off", "stay in"},
            {"stay on", "go over"},
            {"pull over", "stay out"},
            {"stay over", "get somebody down"},
            {"turn in", "stay up"},
            {"take after", "take to"},
            {"get around", "take back"},
            {"take down", "pull in"},
            {"get at", "take in"},
            {"take off", "fall off"},
            {"get on", "take on"},
            {"take over", "pull ahead"},
            {"make for", "take to"},
            {"take up", "make up for"},
            {"get down to", "turn away"},
            {"turn down", "look down on"},
            {"put by", "turn in"},
            {"turn on", "get on"},
            {"come off", "turn out"},
            {"turn over", "come round"},
            {"look over", "turn up"},
            {"work against", "get along"},
            {"make up", "work away at"},
            {"work around", "work off"},
            {"put off", "work off"},
            {"work on", "be on"},
            {"take over", "work out"},
            {"work up", "take to"}};
    String answers[] = {"be about to",
    "be after",
    "be for",
    "be off",
    "be on",
    "be out",
    "be up to",
    "come across",
    "come about",
    "come down",
    "come into",
    "come off",
    "come out",
    "come round",
    "come to",
    "come up",
    "come up to",
    "fall apart",
    "fall back",
    "fall back on",
    "fall behind",
    "fall down",
    "fall for",
    "fall off",
    "fall out with",
    "fall through",
    "give somebody away",
    "give back",
    "give in",
    "give off",
    "give on to",
    "give out",
    "get along",
    "get around",
    "get at",
    "get somebody down",
    "get down to",
    "get on",
    "get over",
    "get round",
    "get through",
    "go around",
    "go back",
    "go down",
    "go in",
    "go into",
    "go off",
    "go on",
    "go over",
    "go to",
    "go up",
    "look down on",
    "look for",
    "look in",
    "look into",
    "look on",
    "look over",
    "look through",
    "look up",
    "look somebody up",
    "look up to",
    "make for",
    "make of",
    "make off",
    "make out",
    "make up one's mind",
    "make up",
    "make up for",
    "pull ahead",
    "pull apart",
    "pull away",
    "pull back",
    "pull down",
    "pull for",
    "pull in",
    "pull off",
    "pull on",
    "pull over",
    "put aside",
    "put away",
    "put by",
    "put down",
    "put forward",
    "put in",
    "put off",
    "put on",
    "put out",
    "put somebody up",
    "put up",
    "put up with",
    "stand about",
    "stand aside",
    "stand back",
    "stand by",
    "stand down",
    "stand for",
    "stand in",
    "stand out",
    "stand up to",
    "stay away",
    "stay behind",
    "stay in",
    "stay on",
    "stay out",
    "stay over",
    "stay up",
    "take after",
    "take back",
    "take down",
    "take in",
    "take off",
    "take on",
    "take over",
    "take to",
    "take up",
    "turn away",
    "turn down",
    "turn in",
    "turn on",
    "turn out",
    "turn over",
    "turn up",
    "work against",
    "work away at",
    "work around",
    "work off",
    "work on",
    "work out",
    "work up"};

    public String getMeaning(int i){
        String meaning = meanings[i];
        return meaning;
    }

    public String getOption1(int i){
        String option1 = options[i][0];
        return option1;
    }

    public String getOption2(int i){
        String option2 = options[i][1];
        return option2;
    }

    public String getAnswer(int i){
        String answer = answers[i];
        return answer;
    }
}
